version: 2
updates:
  - package-ecosystem: npm
    directory: /extension
    schedule:
      interval: weekly
    groups:
      extension:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
